#! /bin/bash
# blackrain at realizedsound dot net
# Andrzej Kopec - akopec at chopin dot edu dot pl - Oct 07 2007
# Dan Stowell Feb 2008 - modifications for non-svn contexts

if [ -d .svn ]; then
  svn export --force build Extensions
else
  cp -uR build Extensions
fi

mv BEQSuiteUGens.so Extensions/BEQSuiteUGens
mv bhob*.so Bhob*.so Extensions/bhobUGens
mv BlackrainUGens.so Extensions/BlackrainUGens
mv Josh*.so Extensions/JoshUGens
mv LoopBuf.so Extensions/ljpclasses
mv MCLD*.so Extensions/MCLD_UGens
mv TagSystemUgens.so Extensions/TagSystemUGens

if [ -f AY*.so ]; then
  mv AY*.so Extensions/MCLD_UGens
fi

# for now disable this
mkdir -p Extensions/MCLD_UGens/test
mv Extensions/MCLD_UGens/MCLD_CQ_UGens.sc Extensions/MCLD_UGens/test

#mkdir Extensions/test
#mv Extensions/StkUGens Extensions/test

#mv StkUGens.so Extensions/StkUGens
#cp -r ../stk-4.2.1/rawwaves Extensions/StkUGens



