#! /bin/sh

svn export --force build Extensions
cp build/BEQSuite*.scx Extensions/BEQSuiteUGens
cp build/bhob*.scx Extensions/bhobUGens
cp build/BlackrainUGens*.scx Extensions/BlackrainUGens
cp build/Josh*.scx Extensions/JoshUGens
cp build/LoopBuf*.scx Extensions/ljpclasses
cp build/MCLD*.scx Extensions/MCLD_UGens
cp build/Membrane*.scx Extensions/MembraneUGens
cp build/MLfftw*.scx Extensions/MLfftwUGens
# cp build/ReverbUGens/*.scx Extensions/ReverbUGens
cp build/RMEQSuite*.scx Extensions/RMEQSuiteUGens
cp build/STK*.scx Extensions/StkUGens
# cp build/TagSystemUGens/*.scx Extensions/TagSystemUGens

mkdir Extensions/test
mv Extensions/StkUGens Extensions/test

# License always important! Plus a readme
cp license.txt Extensions/license.txt
cp Resources/README-for-mac-distro.txt Extensions/README.txt

# Now let's make the disk image
hdiutil create -srcfolder Extensions "SC3ExtPlugins`date +%Y-%m-%d`.dmg" -volname "SC3-plugins"
