#! /bin/bash

echo '********************************************'
echo 'Hello!'
echo '"distro_linux" has been merged with "distro"'
echo 'so in future, please use that instead.'
echo 'Running "distro"...'
echo '********************************************'
./distro

